version: '3'
services:
  webdav:
    build:
      context: webdav
    ports:
      - "127.0.0.1:8888:80"
    volumes:
     - ./data:/webdav
#     - ./data:/var/webdav
  ncwms:
    image: axiom/docker-ncwms
    ports:
      - "127.0.0.1:80:8080"
      - "127.0.0.1:443:8443"
