version: '2'
services:
  webdav:
    build:
      context: webdav
    ports:
      - "127.0.0.1:8888:80"
    container_name: webdav
#  To mount a local directory with data, uncomment this:
#    volumes:
#     - /data:/webdav
  ncwms:
    build:
      context: ncwms
    ports:
      - "127.0.0.1:80:8080"
      - "127.0.0.1:443:8443"
